// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgcrybosdyjkedzoognt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnY3J5Ym9zZHlqa2Vkem9vZ250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODM2NTMsImV4cCI6MjA2Mzg1OTY1M30.Gmgn01ftljo1aA9HSwYje7b2VREcEIbUxQ7WyGoTi-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);